<div class="jumbotron">
    <h1>API <span class="zf-green">TWITTER</span></h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Website</h3>
            </div>
            <div class="panel-body">
                <p>
                </p>
                <p><a class="btn btn-success pull-right" href="/website"> Website &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">URLs</h3>
            </div>
            <div class="panel-body">
                <p>
                </p>

                <p><a class="btn btn-success pull-right" href="/urls">URLs &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Twitter Search API </h3>
            </div>
            <div class="panel-body">
                <p>
                </p>

                <p><a class="btn btn-success pull-right" href="/api">API &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
